# @format

# These are supported funding model platforms

github: TGTGamer # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: # Replace with a single Patreon username
open_collective: smartcloudgg # Replace with a single Open Collective username
liberapay: TGTGamer # Replace with a single Liberapay username
issuehunt: videndum # Replace with a single IssueHunt username
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
