# @format

name: "Smartcloud"
description: "Smartcloud - Github project management automation without limits"
author: "Videndum"
branding:
  icon: "at-sign"
  color: "purple"
inputs:
  GITHUB_TOKEN:
    description: "The GITHUB_TOKEN secret"
    required: true
  config:
    description: "Config file path"
    default: ".github/config.json"
    required: false
  configJSON:
    description: "JSON string with configuration data"
    default: ""
    required: false
  configRef:
    description: "The ref to use when getting the config"
    default: ""
    required: false
  fillEmpty:
    description: "Fill Empty context configuration with shared configs"
    default: "true"
    required: false
  skipDelete:
    description: "Skip deleting labels from repository"
    default: "false"
    required: false
  dryRun:
    description: "Allows the running off action without it doing effects"
    default: "false"
    required: false

runs:
  using: "node12"
  main: "dist/index.js"
