name: 'Release Mastermind'
description: ''
author: 'Videndum'
branding:
  icon: 'at-sign'
  color: 'purple'
inputs:
  GITHUB_TOKEN:
    description: 'The GITHUB_TOKEN secret'
    required: true
  config:
    description: 'Config file path'
    default: '.github/config.json'
    required: false
  configJSON:
    description: 'JSON string with configuration data'
    default: ''
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
