name: Project Management
on:
  project_card:
    types: [created, moved, deleted]
jobs:
  # Automatically assigns labels based on config ../card-labeler.yml
  triage:
    name: Auto card labeler
    runs-on: ubuntu-latest
    steps:
      - name: Get Configurations
        uses: ./variable-mastermind/
        with:
          settings: ${{ secrets.SETTINGS }}
          mode: 'environment'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Adjust Lables
        if: ${{env.projects_enabled}} == true
        uses: technote-space/auto-card-labeler@v1
        with:
          CONFIG_FILENAME: ${{env.projects_cardsConfig}}
