# name: Release Management

# on:
#   push:
#     branches:
#       - master
#       - dev
#   gollum:

# jobs:
#   # syncs from the github inbuilt wiki
#   job-sync-wiki-to-docs:
#     name: Sync from wiki
#     runs-on: ubuntu-latest
#     if: github.event_name == 'gollum'
#     steps:
#       - name: Get Configurations
#         uses: Videndum/manage-github-secrets@1.0.0-beta
#         with:
#           settings: ${{ secrets.SETTINGS }}
#           mode: 'environment'
#           token: ${{ secrets.GITHUB_TOKEN }}
#       - uses: peterjgrainger/action-create-branch@2.0.1
#         if: ${{env.wiki_enabled}} == true
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         with:
#           branch: ${{env.auto_branchPrefix}}${{env.auto_branch}}_wiki
#       - name: Checkout Repo
#         if: ${{env.wiki_enabled}} == true
#         uses: actions/checkout@v2
#         with:
#           token: ${{ secrets.GITHUB_TOKEN }}
#           ref: ${{env.auto_branchPrefix}}${{env.auto_branch}}_wiki
#       - name: Sync Wiki to Docs
#         uses: newrelic/wiki-sync-action@master
#         with:
#           source: ${{env.wiki_docsToWikiDestination}}
#           destination: ${{env.wiki_docsToWikiSource}}
#           token: ${{ secrets.BOT_TOKEN }}
#           branch: ${{env.auto_branchPrefix}}${{env.auto_branch}}_wiki
#       - name: pull-request
#         if: ${{env.wiki_enabled}} == true && ${{env.wiki_wikiToDocs}} == true
#         uses: repo-sync/pull-request@v2
#         with:
#           github_token: ${{ secrets.BOT_TOKEN }}
#           source_branch: ${{env.auto_branchPrefix}}${{env.auto_branch}}_wiki
#           destination_branch: ${{env.auto_destination}}
#           pr_title: ${{env.wiki_wikiToDocsPRtitle}}
#           pr_body: ${{env.auto_body}}
#           pr_label: ${{env.auto_labels}}
#       - run: echo ::set-env name=repository_name::$(echo "${{github.repository}}" | awk -F / '{print $2}')
#       - name: Copy to ${{github.repository}}
#         if: ${{env.wiki_enabled}} == true && ${{env.wiki_wikiToRepo}} == true
#         uses: andstor/copycat-action@v3
#         with:
#           personal_token: ${{ secrets.BOT_TOKEN }}
#           src_path: ${{env.wiki_docsToRepoSource}}
#           dst_path: /${{env.wiki_docsToRepoDestination}}
#           dst_owner: ${{github.repository_owner}}
#           dst_repo_name: ${{env.repository_name}}${{env.wiki_docsToRepoSuffix}}
#           commit_message: 'docs: auto update'
#         continue-on-error: true
