version: 3
pullapprove_conditions:
  - condition: "base.ref == 'master'"
    unmet_status: success
    explanation: "Review not required unless merging to master"
  - condition: "body and '- [ ]' not in body"
    unmet_status: pending
    explanation: "Please finish all the tasks first (must have PR body)"
  - condition: "'security fix' not in labels"

notifications:
  - when: pull_request.opened
    if: "author_association == 'FIRST_TIME_CONTRIBUTOR'"
    comment: |
      Hey @{{ author }}, thanks for the PR! The review will start once the tests and CI checks have passed. If they don't, please review the logs and try to fix the issues (ask for help if you can't figure it out). 
      A reviewer will be assigned once the tests arepassing and they'll walk you through getting the PR finished and merged.
  - when: pull_request.opened
    if: "author_association == 'CONTRIBUTOR'"
    comment: |
      Hey @{{ author }}, thanks for the PR! The review will start once the tests and CI checks have passed.
  - when: pullapprove.approved
    if: "author_association == 'CONTRIBUTOR'"
    comment: "The review is completed. Thanks @{{ author }}, we'll take it from here."

groups:
  # Global team for reviewing code - Can override other groups to do instant pulls
  global:
    type: optional
    reviewers:
      teams:
      - admins
    reviews:
      request: 0
      required: 1
      reviewed_for: required

  # All public reviews are marked as optional
  public:
    type: optional
    reviews:
      required: 1

  # The design team for reviewing deisng changes.
  # Uses lables:
  design:
    conditions:
    - "'ui/ux' in labels"
    reviewers:
      teams:
      - design

  # Changing this file requires ADMIN approval
  pullapprove:
    conditions:
    - "'.pullapprove.yml' in files"
    reviewers:
      teams:
      - admins
    reviews:
      required: 1