# @format

name: Contributor License Agreement Management
on:
  issue_comment:
    types: [created]
  pull_request:
    types: [opened, synchronize]

# Ensures the CLA is signed
jobs:
  CLAssistant:
    name: "CLA Assistant"
    runs-on: ubuntu-latest
    if: (github.event.comment.body == 'recheckcla' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA' || github.event_name == 'pull_request' )
    steps:
      - name: CLA Assistant
        if: ${{env.cla_enabled}} == true
        uses: cla-assistant/github-action@v2.1.3-beta
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path-to-signatures: ".github/cla.json"
          path-To-cladocument: "https://github.com/${{github.repository}}/docs/getting-started/contributing/CODE_OF_CONDUCT.md"
          label: true
          whitelist: "dependabot[bot], dependabot-preview[bot], github-actions[bot], github-actions, github-user, actions-user, web-flow, VidendumStudios"
        continue-on-error: true
