# @format

name: Test documentation update

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/deploy.yml"
      - "docs/**"
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    defaults:
      run:
        working-directory: docs
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-docs-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-docs-

      - name: install smartcloud dependencies
        run: yarn install --frozen-lockfile

      - run: yarn install --frozen-lockfile
        working-directory: docs
        
      - run: yarn build
        working-directory: docs
