name: Project Management
on:
  project_card:

jobs:
  release-mastermind:
    name: Release Mastermind
    runs-on: ubuntu-latest
    steps:          
      - uses: actions/checkout@v2.3.1
      - uses: ./packages/release-mastermind/
        with:
          GITHUB_TOKEN: '${{ secrets.BOT_TOKEN }}'
          config: .github/allconfigs.json
