# @format

name: Test Actions
on:
  pull_request_review:
    types: [submitted]

jobs:
  release-mastermind:
    name: Release Mastermind
    runs-on: ubuntu-latest
    if: ${{ github.event.review.state == 'approved'}}
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: ./

        with:
          GITHUB_TOKEN: "${{ secrets.BOT_TOKEN }}"
          config: .github/config/labelMastermind.json
          dryRun: true
          configRef: develop
